name: default
permissions:
- ChestShop.shop.*
- hat.*
- jetshoppers.default.*
- mypet.extended.behavior.*
- mypet.leash.*
- ChatManager.Bypass.AntiAdvertising
- ChatManager.Message
- arena.arena.join
- arena.duel
- backpack.clean
- backpack.size.4
- backpack.use
- bountyhunters.add
- bountyhunters.claim
- bountyhunters.leaderboard
- bountyhunters.list
- bountyhunters.quote
- bountyhunters.redeem-heads
- bountyhunters.title
- brewery.cmd.info
- brewery.user
- bukkit.command.version:
    value: false
- chatmanager.lists
- chatmanager.reply
- chestshop
- chestshop.iteminfo
- chestsort.use
- chestsort.use.inventory
- citizens.npc.talk
- claimchunk.access
- claimchunk.base
- claimchunk.claim
- claimchunk.unclaim
- cristreecapitator.user
- editablesign.colorsign
- editablesign.edit
- essentials.afk
- essentials.afk.auto
- essentials.afk.message
- essentials.back
- essentials.back.ondeath
- essentials.balance
- essentials.balancetop
- essentials.clearinventory
- essentials.compass
- essentials.delhome
- essentials.depth
- essentials.disposal
- essentials.help
- essentials.home
- essentials.ignore
- essentials.info
- essentials.itemdb
- essentials.list
- essentials.mail
- essentials.motd
- essentials.msg
- essentials.msgtoggle
- essentials.near
- essentials.pay
- essentials.ping
- essentials.r
- essentials.realname
- essentials.sell
- essentials.sell.bulk
- essentials.sell.hand
- essentials.sethome
- essentials.spawn
- essentials.suicide
- essentials.time
- essentials.tpa
- essentials.tpacancel
- essentials.tpaccept
- essentials.tpahere
- essentials.tpdeny
- essentials.vanish:
    value: false
- essentials.warp
- essentials.warp.auctionhouse
- essentials.warp.list
- essentials.warps
- essentials.warps.AdminShop
- essentials.warps.mallmart
- globalwarming.score
- globalwarming.score.alerts
- globalwarming.score.book
- globalwarming.score.hide
- globalwarming.score.show
- globalwarming.score.top
- grapplinghook.craft
- hoppers.place.default
- infobook.get
- infobook.list
- lottery.buy
- lottery.gui
- lottery.status
- lottery.ticketlimit.20
- lottery.togglebuymsg
- lottery.toggleremindmsg
- mypet.command.capturehelper
- mypet.command.info
- mypet.command.name
- mypet.command.name.color
- mypet.command.release
- mypet.command.respawn
- mypet.command.store
- mypet.command.switch
- mypet.extended.beacon
- mypet.extended.behavior.aggressive
- mypet.extended.behavior.duel
- mypet.extended.behavior.farm
- mypet.extended.behavior.friendly
- mypet.extended.behavior.raid
- mypet.extended.control
- mypet.extended.equip
- mypet.extended.feed
- mypet.extended.inventory
- mypet.extended.nametag
- mypet.extended.pickup
- mypet.extended.ride
- mypet.petstorage.limit.3
- mypet.skilltree.combat
- mypet.skilltree.farm
- mypet.skilltree.pvp
- mypet.skilltree.ride
- mypet.skilltree.utility
- npcauctions.auctionlimit.50
- npcauctions.openGUIFromCommand:
    value: false
- simpleportals.portal.
- simpleportals.portal.egototemple
- simpleportals.portal.lionjettatotemple
- simpleportals.portal.spawntotrainstation1
- simpleportals.portal.templeego
- simpleportals.portal.templeportal1
- simpleportals.portal.templetoego
- simpleportals.portal.templetolionjetta
- simpleportals.portals.TempletoCahlle
- simpleportals.portals.arena1
- simpleportals.portals.cahlletotemple
- simpleportals.portals.durmhouse
- simpleportals.portals.riptide
- simpleportals.portals.templeportalout1
- simpleportals.portals.templeriptide
- sv.see:
    value: false
